version: "3.8"

services:

  frontend:
   build: ../../material-applications/example-frontend/
   ports:
    - 3000:5000
   environment:
    - REACT_APP_BACKEND_URL=http://localhost:5000/

  backend:
   build: ../../material-applications/example-backend/
   ports:
     - 5000:8000
   environment:
     - REQUEST_ORIGIN=http://localhost:3000
     - REDIS_HOST=redis
     - POSTGRES_HOST=db
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=1234
     - POSTGRES_DATABASE=db_app

  redis:
    image: redis:7.0.15-alpine3.20

  db:
   image: postgres:alpine3.20
   restart: unless-stopped
   environment:
    - POSTGRES_PASSWORD=1234
    - POSTGRES_USER=admin
    - POSTGRES_DB=db_app
   volumes:
    - type: bind
      source: ./database
      target: /var/lib/postgresql/data


  nginx:
    image: nginx:1.27
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    
    ports:
      - 80:80
