# select base image
FROM node:16

WORKDIR /usr/src/app

COPY package* .

#install all dependencies
RUN npm ci

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost/api/

EXPOSE 5000

RUN npm run build

RUN npm install -g serve

CMD serve -s -l 5000 build
