version: "3.8"

services:
  
  frontend:
   build:
    context: .
    dockerfile: Dockerfile-frontend
   ports:
    - 3000:5000
   environment:
    - REACT_APP_BACKEND_URL=http://localhost:5000/

  backend:
   build:
    context: .
    dockerfile: Dockerfile-backend 
   ports:
     - 5000:8000
   environment:
     - REQUEST_ORIGIN=http://localhost:3000
